<a href="https://colab.research.google.com/github/mohammedaman0908/ML_Colab_Projects/blob/main/Assignment_05_COE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd


url = '/content/Titanic-Dataset.csv'
data = pd.read_csv(url)
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:

data.info()


data.isnull().sum()


data.describe()


data['Sex'].value_counts()
data['Embarked'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [3]:

data['Age'].fillna(data['Age'].median(), inplace=True)


data['Embarked'].fillna(data['Embarked'].mode()[0], inplace=True)


data['Has_Cabin'] = data['Cabin'].apply(lambda x: 0 if pd.isnull(x) else 1)


data.drop('Cabin', axis=1, inplace=True)

In [4]:

data.duplicated().sum()


data.drop_duplicates(inplace=True)

In [5]:

data['Title'] = data['Name'].apply(lambda x: x.split(',')[1].split('.')[0].strip())


data['Title'] = data['Title'].replace(['Lady', 'Countess','Capt', 'Col', 'Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')
data['Title'] = data['Title'].replace('Mlle', 'Miss')
data['Title'] = data['Title'].replace('Ms', 'Miss')
data['Title'] = data['Title'].replace('Mme', 'Mrs')


data.drop('Name', axis=1, inplace=True)

In [6]:

data['Family_Size'] = data['SibSp'] + data['Parch'] + 1

In [7]:

data['IsAlone'] = 1  # initialize to 1
data['IsAlone'].loc[data['Family_Size'] > 1] = 0  # update to 0 if not alone

<ipython-input-7-b4b66fba559b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['IsAlone'].loc[data['Family_Size'] > 1] = 0  # update to 0 if not alone

In [8]:

data['Sex'] = data['Sex'].map({'male': 0, 'female': 1})

In [9]:

data = pd.get_dummies(data, columns=['Embarked', 'Title'], drop_first=True)

In [10]:
from sklearn.preprocessing import StandardScaler


num_features = ['Age', 'Fare', 'Family_Size']


scaler = StandardScaler()
data[num_features] = scaler.fit_transform(data[num_features])

In [11]:

data.drop(['PassengerId', 'Ticket'], axis=1, inplace=True)

In [12]:

X = data.drop('Survived', axis=1)
y = data['Survived']

In [13]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)